# Generated by Django 4.0 on 2024-06-04 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('intensity', models.CharField(max_length=25)),
                ('muscles', models.CharField(max_length=25)),
                ('day', models.CharField(max_length=15)),
                ('sets', models.IntegerField(default=3)),
                ('reps_min', models.IntegerField(default=8)),
                ('reps_max', models.IntegerField(default=12)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]